name: CI & Release

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight UTC
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: installable-sh/docker/.github/workflows/ci.yml@main

  release:
    needs: [ci]
    uses: installable-sh/docker/.github/workflows/release.yml@main
    permissions:
      contents: write

  build:
    needs: [ci, release]
    if: always() && needs.ci.result == 'success'
    uses: installable-sh/docker/.github/workflows/docker.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image-name: ghcr.io/installable-sh/run
      new-tag: ${{ needs.release.outputs.new_tag }}
      major-tag: ${{ needs.release.outputs.major_tag }}
